// ==========================================
// قاعدة بيانات البرامج - Software Database
// ==========================================

const appsData = [
    {
        id: 1,
        name: "DzCEM Results",
        nameAr: "نتائج متوسط DzCEM",
        category: "متوسط",
        categoryEn: "Middle School",
        icon: "../images/DzCEM Results Setup 1.0.0.png",
        gradient: "linear-gradient(135deg, #6366f1, #8b5cf6)",
        color: "#6366f1",
        version: "1.0.0",
        size: "73.7 MB",
        fileName: "DzCEM Results Setup 1.0.0.exe",
        description: "برنامج متكامل لإدارة وعرض نتائج التلاميذ في الطور المتوسط مع تقارير مفصلة وإحصائيات دقيقة.",
        descriptionEn: "Integrated software for managing and displaying middle school student results with detailed reports and statistics.",
        features: ["عرض نتائج التلاميذ", "تقارير مفصلة", "إحصائيات دقيقة", "واجهة سهلة الاستخدام"],
        featuresEn: ["Display student results", "Detailed reports", "Accurate statistics", "User-friendly interface"],
        downloads: 12450
    },
    {
        id: 2,
        name: "DzCEM Calculator",
        nameAr: "حاسبة المعدلات DzCEM",
        category: "متوسط",
        categoryEn: "Middle School",
        icon: "../images/DzCEM Calculator Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #3b82f6, #6366f1)",
        color: "#3b82f6",
        version: "1.0.0",
        size: "73.6 MB",
        fileName: "DzCEM Calculator Setup 1.0.0.exe",
        description: "حاسبة المعدلات الفصلية والسنوية للطور المتوسط وفق المنهاج الجزائري مع حساب تلقائي دقيق.",
        descriptionEn: "Calculator for term and annual averages for middle school according to the Algerian curriculum with precise automatic calculation.",
        features: ["حساب المعدلات الفصلية", "حساب المعدل السنوي", "وفق المنهاج الجزائري", "نتائج فورية"],
        featuresEn: ["Term averages calculation", "Annual average calculation", "Algerian curriculum compliant", "Instant results"],
        downloads: 9800
    },
    {
        id: 3,
        name: "DzExam Generator",
        nameAr: "مولد الامتحانات DzExam",
        category: "متوسط",
        categoryEn: "Middle School",
        icon: "../images/DzExam Generator Setup 1.0.0.png",
        gradient: "linear-gradient(135deg, #10b981, #059669)",
        color: "#10b981",
        version: "1.0.0",
        size: "73.6 MB",
        fileName: "DzExam Generator Setup 1.0.0.exe",
        description: "أداة ذكية لتوليد الامتحانات والاختبارات بشكل آلي وفق المنهاج الجزائري مع تخصيص كامل.",
        descriptionEn: "Smart tool for automatically generating exams and tests according to the Algerian curriculum with full customization.",
        features: ["توليد امتحانات آلي", "تخصيص الأسئلة", "وفق المنهاج الجزائري", "تصدير جاهز للطباعة"],
        featuresEn: ["Auto exam generation", "Questions customization", "Algerian curriculum", "Print-ready export"],
        downloads: 8700
    },
    {
        id: 4,
        name: "DzFET Print",
        nameAr: "طباعة جداول التوقيت DzFET",
        category: "إدارة وتسيير",
        categoryEn: "Administration",
        icon: "../images/DzFET Print Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
        color: "#f59e0b",
        version: "1.0.0",
        size: "73.6 MB",
        fileName: "DzFET Print Setup 1.0.0.exe",
        description: "برنامج متخصص في طباعة وتنسيق جداول التوقيت المدرسية بشكل احترافي ومنظم.",
        descriptionEn: "Specialized software for professionally printing and formatting school timetables.",
        features: ["طباعة جداول التوقيت", "تنسيق احترافي", "دعم جميع الأطوار", "تصدير PDF"],
        featuresEn: ["Print timetables", "Professional formatting", "Supports all levels", "PDF Export"],
        downloads: 7500
    },
    {
        id: 5,
        name: "DzSahel Admin",
        nameAr: "تسهيل الإدارة DzSahel",
        category: "إدارة وتسيير",
        categoryEn: "Administration",
        icon: "../images/DzSahel Admin Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #ec4899, #be185d)",
        color: "#ec4899",
        version: "1.0.0",
        size: "73.7 MB",
        fileName: "DzSahel Admin Setup 1.0.0.exe",
        description: "نظام إداري شامل يسهل عمليات التسيير والإدارة المدرسية مع أدوات متقدمة.",
        descriptionEn: "Comprehensive management system facilitating school administration with advanced tools.",
        features: ["إدارة شاملة", "تسيير الملفات", "تقارير إدارية", "أدوات متقدمة"],
        featuresEn: ["Comprehensive management", "File handling", "Administrative reports", "Advanced tools"],
        downloads: 15200
    },
    {
        id: 6,
        name: "DzTutor Physics",
        nameAr: "معلم الفيزياء DzTutor",
        category: "متوسط",
        categoryEn: "Middle School",
        icon: "../images/DzTutor Physics Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #14b8a6, #0d9488)",
        color: "#14b8a6",
        version: "1.0.0",
        size: "73.6 MB",
        fileName: "DzTutor Physics Setup 1.0.0.exe",
        description: "مساعد تعليمي ذكي لمادة الفيزياء في الطور المتوسط مع شروحات وتمارين تفاعلية.",
        descriptionEn: "Smart educational assistant for Physics in middle school with interactive explanations and exercises.",
        features: ["شروحات تفاعلية", "تمارين محلولة", "وفق المنهاج الجزائري", "واجهة بسيطة"],
        featuresEn: ["Interactive explanations", "Solved exercises", "Algerian curriculum", "Simple interface"],
        downloads: 11000
    },
    {
        id: 7,
        name: "Nojoom DZ",
        nameAr: "نجوم الجزائر",
        category: "ابتدائي",
        categoryEn: "Primary School",
        icon: "../images/Nojoom DZ Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #f97316, #ea580c)",
        color: "#f97316",
        version: "1.0.0",
        size: "73.6 MB",
        fileName: "Nojoom DZ Setup 1.0.0.exe",
        description: "برنامج تعليمي تفاعلي مخصص لتلاميذ الطور الابتدائي مع أنشطة تعليمية ممتعة.",
        descriptionEn: "Interactive educational software dedicated to primary school students with fun learning activities.",
        features: ["أنشطة تفاعلية", "مخصص للابتدائي", "تعليم ممتع", "واجهة ملونة للأطفال"],
        featuresEn: ["Interactive activities", "Primary school focus", "Fun learning", "Colorful kids UI"],
        downloads: 18500
    },
    {
        id: 8,
        name: "Quran App",
        nameAr: "تطبيق القرآن الكريم",
        category: "برامج عامة",
        categoryEn: "General",
        icon: "../images/Quran App Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #059669, #047857)",
        color: "#059669",
        version: "1.0.0",
        size: "73.8 MB",
        fileName: "Quran App Setup 1.0.0.exe",
        description: "تطبيق شامل للقرآن الكريم مع تلاوة وتفسير وبحث متقدم وواجهة عصرية أنيقة.",
        descriptionEn: "Comprehensive Holy Quran app featuring recitation, tafsir, advanced search, and a modern UI.",
        features: ["تلاوة القرآن الكريم", "تفسير الآيات", "بحث متقدم", "واجهة عصرية"],
        featuresEn: ["Quran recitation", "Ayah Tafsir", "Advanced search", "Modern UI"],
        downloads: 22000
    },
    {
        id: 9,
        name: "AIO Software Installer",
        nameAr: "مثبت البرامج الشامل",
        category: "أدوات",
        categoryEn: "Tools",
        icon: "../images/AIO Software Installer Setup 1.0.0.ico",
        gradient: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
        color: "#8b5cf6",
        version: "1.0.0",
        size: "73.5 MB",
        fileName: "AIO Software Installer Setup 1.0.0.exe",
        description: "أداة شاملة لتثبيت مجموعة من البرامج الأساسية دفعة واحدة بسهولة وسرعة.",
        descriptionEn: "All-in-one tool to easily and quickly install a batch of essential software.",
        features: ["تثبيت دفعي", "برامج أساسية", "سهل الاستخدام", "توفير الوقت"],
        featuresEn: ["Batch installation", "Essential software", "Easy to use", "Time-saving"],
        downloads: 13200
    },
    {
        id: 10,
        name: "Attendance Setup",
        nameAr: "نظام الحضور والغياب",
        category: "إدارة وتسيير",
        categoryEn: "Administration",
        icon: "default",
        gradient: "linear-gradient(135deg, #06b6d4, #0891b2)",
        color: "#06b6d4",
        version: "1.0.0",
        size: "76.8 MB",
        fileName: "Attendance_Setup.exe",
        description: "نظام متكامل لتسجيل ومتابعة حضور وغياب التلاميذ مع تقارير يومية وشهرية.",
        descriptionEn: "Integrated system for recording and tracking student attendance with daily and monthly reports.",
        features: ["تسجيل الحضور", "تقارير يومية", "متابعة الغياب", "إحصائيات شهرية"],
        featuresEn: ["Record attendance", "Daily reports", "Track absences", "Monthly statistics"],
        downloads: 6300
    },
    {
        id: 11,
        name: "Office Unlocker",
        nameAr: "فتح ملفات الأوفيس",
        category: "أدوات",
        categoryEn: "Tools",
        icon: "../images/Office_Unlocker_Offline_Setup.png",
        gradient: "linear-gradient(135deg, #ef4444, #dc2626)",
        color: "#ef4444",
        version: "1.0.0",
        size: "26.3 MB",
        fileName: "Office_Unlocker_Offline_Setup.exe",
        description: "أداة لفتح وإلغاء حماية ملفات Microsoft Office المقفلة بدون اتصال بالإنترنت.",
        descriptionEn: "Offline tool to unlock and remove protection from locked Microsoft Office files.",
        features: ["فتح ملفات مقفلة", "بدون إنترنت", "دعم Word و Excel", "سريع وآمن"],
        featuresEn: ["Unlock locked files", "Offline use", "Supports Word & Excel", "Fast & Secure"],
        downloads: 9500
    },
    {
        id: 12,
        name: "Web2App Converter",
        nameAr: "محول المواقع إلى تطبيقات",
        category: "أدوات",
        categoryEn: "Tools",
        icon: "../images/Web2App_Converter_Free_Setup.ico",
        gradient: "linear-gradient(135deg, #a855f7, #9333ea)",
        color: "#a855f7",
        version: "Free",
        size: "33.3 MB",
        fileName: "Web2App_Converter_Free_Setup.exe",
        description: "أداة لتحويل أي موقع ويب إلى تطبيق سطح مكتب مستقل بسهولة تامة.",
        descriptionEn: "Tool to easily convert any website into a standalone desktop application.",
        features: ["تحويل المواقع", "تطبيقات مستقلة", "سهل الاستخدام", "نسخة مجانية"],
        featuresEn: ["Convert websites", "Standalone apps", "Easy to use", "Free version"],
        downloads: 16800
    },
    {
        id: 13,
        name: "Marks Notes Adder",
        nameAr: "برنامج إدراج الملاحظات",
        category: "إدارة وتسيير",
        categoryEn: "Administration",
        icon: "default",
        gradient: "linear-gradient(135deg, #f472b6, #ec4899)",
        color: "#f472b6",
        version: "1.0.0",
        size: "75.6 MB",
        fileName: "برنامج إدراج الملاحظات Setup 1.0.0.exe",
        description: "برنامج متخصص في إدراج وإدارة الملاحظات على كشوف النقاط والوثائق المدرسية.",
        descriptionEn: "Specialized software for inserting and managing remarks on report cards and school documents.",
        features: ["إدراج ملاحظات", "كشوف النقاط", "إدارة الوثائق", "طباعة احترافية"],
        featuresEn: ["Insert remarks", "Report cards", "Document management", "Professional printing"],
        downloads: 8200
    },
    {
        id: 14,
        name: "Primary Marks Entry",
        nameAr: "حجز النقاط - ابتدائي",
        category: "ابتدائي",
        categoryEn: "Primary School",
        icon: "default",
        gradient: "linear-gradient(135deg, #fbbf24, #f59e0b)",
        color: "#fbbf24",
        version: "1.0.0",
        size: "91.8 MB",
        fileName: "برنامج حجز النقاط - إبتدائي.zip",
        description: "برنامج حجز وتسجيل نقاط التلاميذ في الطور الابتدائي وفق النظام الجزائري.",
        descriptionEn: "Software for recording primary school student marks according to the Algerian system.",
        features: ["حجز النقاط", "الطور الابتدائي", "نظام جزائري", "سهل الاستخدام"],
        featuresEn: ["Marks entry", "Primary level", "Algerian system", "Easy to use"],
        downloads: 14300
    },
    {
        id: 15,
        name: "Middle Marks Entry",
        nameAr: "حجز النقاط - متوسط",
        category: "متوسط",
        categoryEn: "Middle School",
        icon: "default",
        gradient: "linear-gradient(135deg, #2dd4bf, #14b8a6)",
        color: "#2dd4bf",
        version: "1.0.0",
        size: "91.8 MB",
        fileName: "برنامج حجز النقاط - متوسط.zip",
        description: "برنامج حجز وتسجيل نقاط التلاميذ في الطور المتوسط وفق النظام الجزائري.",
        descriptionEn: "Software for recording middle school student marks according to the Algerian system.",
        features: ["حجز النقاط", "الطور المتوسط", "نظام جزائري", "تقارير مفصلة"],
        featuresEn: ["Marks entry", "Middle level", "Algerian system", "Detailed reports"],
        downloads: 13100
    },
    {
        id: 16,
        name: "Middle Marks (Enhanced)",
        nameAr: "حجز النقاط طور متوسط - النسخة المحسنة",
        category: "متوسط",
        categoryEn: "Middle School",
        icon: "default",
        gradient: "linear-gradient(135deg, #4ade80, #22c55e)",
        color: "#4ade80",
        version: "2.0.0",
        size: "96.3 MB",
        fileName: "حجز النقاط طور متوسط - النسخة المحسنة.exe",
        description: "النسخة المحسنة والمطورة من برنامج حجز النقاط للطور المتوسط بمزايا إضافية ومحسنة.",
        descriptionEn: "Enhanced version of the middle school marks entry software with improved features.",
        features: ["نسخة محسنة", "مزايا إضافية", "أداء أفضل", "واجهة محدثة"],
        featuresEn: ["Enhanced version", "Extra features", "Better performance", "Updated UI"],
        downloads: 17600
    }
];

// تصنيفات البرامج
const categories = [
    { ar: "الكل", en: "All" },
    { ar: "متوسط", en: "Middle School" },
    { ar: "ابتدائي", en: "Primary School" },
    { ar: "إدارة وتسيير", en: "Administration" },
    { ar: "أدوات", en: "Tools" },
    { ar: "برامج عامة", en: "General" }
];
